markdown: kramdown

### Site info:
baseurl: /bettina-st/
author: Bettina Stingelin
title: Bettina Stingelin writer
email: ""
description: > # this means to ignore newlines until "baseurl:"

### App info:
exclude: ['README.md', 'Gemfile.lock', 'vendor']
