---
title: Bettina Stingelin Writer
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  paginas:
    title: Páginas
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
baseurl: "/bettina-st"
author: Bettina Stingelin
email: 
description: Bettina's web site
exclude:
- README.md
- Gemfile.lock
- vendor
