markdown: kramdown

### Site info:
baseurl: /bettina-st
author: Bettina Stingelin
title: Bettina Stingelin Writer
email: ""
description: "Bettina's web site"

### App info:
exclude: ['README.md', 'Gemfile.lock', 'vendor']
